name: Draw ZMK keymaps

on:
    push:
        paths:
            - "boards/shields/klor/*.keymap"
            - "boards/shields/klor/*.dtsi"


jobs:
    draw:
        uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
        permissions:
            contents: write
        with:
            keymap-patterns: "boards/shields/klor/*.keymap"
            config_path: "keymap_drawer.config.yaml"
            output_folder: "keymap-drawer"
            parse_args: ""
            draw_args: ""